# Generated by Django 2.2.12 on 2022-06-26 18:37

from django.db import migrations, models
import django.db.models.deletion
import mytest.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(default=mytest.models.code_generator, editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('weight', models.FloatField()),
                ('description', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Progress', 'Progress'), ('Done', 'Done')], default='Pending', max_length=8)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('debitCash', 'debitCash'), ('creditRevenue', 'creditRevenue'), ('creditPayable', 'creditPayable')], max_length=14)),
                ('amount', models.FloatField()),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytest.Shipment')),
            ],
        ),
    ]
